# Generated by Django 5.1 on 2024-09-18 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('Complaint', 'Complaint'), ('Suggestion', 'Suggestion'), ('Compliment', 'Compliment')], help_text='Type of feedback: Complaint, Suggestion, Compliment', max_length=255)),
                ('feedback', models.TextField(help_text='Feedback message')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], help_text='Status of the feedback: Pending, Resolved', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this feedback was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this feedback was last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
