# Generated by Django 5.1 on 2024-09-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AlterField(
            model_name='course',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_level_course', to='core.classlevel'),
        ),
    ]
