# Generated by Django 5.1 on 2024-08-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_created_at_alter_course_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enrollment_date',
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teachingrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
