# Generated by Django 5.1 on 2024-09-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_semester_remove_course_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, help_text='Lecturer teaching the course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_lecturer', to='core.lecturer'),
        ),
    ]
