# Generated by Django 5.1 on 2024-09-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='encrypted_data',
            field=models.TextField(blank=True, help_text='Encrypted data for the QR code', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', help_text='Status of the feedback: Pending, Resolved', max_length=255),
        ),
    ]
