# Generated by Django 5.1 on 2024-09-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('level', 'group', 'semester', 'year')},
        ),
    ]
