# Generated by Django 5.1 on 2024-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_enrollment_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matricule',
            field=models.CharField(default='ICTUXXXXxxxx', max_length=255),
        ),
    ]
