# Generated by Django 5.1 on 2024-09-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_course_semester_remove_course_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(default='ICTUXXXXxxxx', help_text='Student number', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('class_level', 'student_number')},
        ),
    ]
