# Generated by Django 5.1 on 2024-09-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_lecturer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('level', 'group', 'semester', 'year')},
        ),
    ]
