# Generated by Django 5.1 on 2024-09-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_encrypted_data_alter_feedback_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='encrypted_data',
        ),
        migrations.AddField(
            model_name='student',
            name='encoded_data',
            field=models.TextField(blank=True, help_text='Encoded data for the QR code', null=True),
        ),
    ]
