# Generated by Django 5.1 on 2024-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='finish_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='arrival',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='departure',
            field=models.TimeField(),
        ),
    ]
