# Generated by Django 5.1 on 2024-09-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_encoded_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='encoded_data',
            field=models.TextField(blank=True, editable=False, help_text='Encoded data for the QR code', null=True, unique=True),
        ),
    ]
