# Generated by Django 5.1 on 2024-08-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_course_finish_time_remove_lecturer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_delegate',
            field=models.ForeignKey(blank=True, help_text='Student delegate in charge of this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_delegate', to='core.student'),
        ),
    ]
