# Generated by Django 5.1 on 2024-12-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_courseregistration_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(blank=True, help_text="Lecturer's email address", max_length=254, null=True, unique=True),
        ),
    ]
