# Generated by Django 5.1 on 2024-12-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lecturer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(help_text="Lecturer's email address", max_length=254, unique=True),
        ),
    ]
