# Generated by Django 5.1 on 2024-12-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_lecturer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='Gender of the lecturer: Male or Female', max_length=255),
        ),
    ]
