# Generated by Django 5.1 on 2024-08-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_course_student_delegate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_delegate_assistant',
        ),
    ]
