# Generated by Django 5.1 on 2024-08-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_course_student_delegate_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_delegate_assistant',
            field=models.ForeignKey(blank=True, help_text='Student delegate assistant in charge of this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_delegate_assistant', to='core.student'),
        ),
    ]
