# Generated by Django 5.1 on 2024-08-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_student_delegate_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(editable=False, help_text='Duration of the course (automatically calculated)'),
        ),
    ]
