# Generated by Django 5.1 on 2024-08-23 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(help_text='Duration of the course (Automatically calculated)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_delegate',
            field=models.ForeignKey(blank=True, help_text='Student delegate in charge of this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_delegate', to='core.student'),
        ),
    ]
