# Generated by Django 5.1 on 2024-08-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_course_student_delegate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'verbose_name': 'Lecturer', 'verbose_name_plural': 'Lecturers'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teachingrecord',
            options={'verbose_name': 'Teaching Record', 'verbose_name_plural': 'Teaching Records'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_delegate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_delegate_assistant',
        ),
        migrations.CreateModel(
            name='StudentDelegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('delegate', 'Delegate'), ('assistant', 'Assistant')], default='delegate', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates_course', to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates_student', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Delegate',
                'verbose_name_plural': 'Student Delegates',
                'unique_together': {('student', 'course', 'role')},
            },
        ),
    ]
