# Generated by Django 5.1 on 2024-08-23 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_course_options_alter_lecturer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdelegate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdelegate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentdelegate',
            name='role',
            field=models.CharField(choices=[('delegate', 'Delegate'), ('assistant', 'Assistant')], default='delegate', max_length=100),
        ),
    ]
