# Generated by Django 5.1 on 2024-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_studentdelegate_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time this course was added'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this course was last updated'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time this enrollment was added'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this enrollment was last updated'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time this lecturer was added'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this lecturer was last updated'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time this student was added'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this student was last updated'),
        ),
        migrations.AlterField(
            model_name='studentdelegate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time this student delegate was added'),
        ),
        migrations.AlterField(
            model_name='studentdelegate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this student delegate was last updated'),
        ),
        migrations.AlterField(
            model_name='teachingrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time this teaching record was added'),
        ),
        migrations.AlterField(
            model_name='teachingrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this teaching record was last updated'),
        ),
    ]
