# Generated by Django 5.1 on 2024-08-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_course_created_at_alter_course_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', editable=False, help_text='Slug of the course', max_length=255),
            preserve_default=False,
        ),
    ]
