# Generated by Django 5.1 on 2024-08-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_enrollment_options_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingrecord',
            name='quality_assurance',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], help_text='Quality assurance of the course', max_length=255, null=True),
        ),
    ]
