# Generated by Django 5.1 on 2024-08-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_teachingrecord_quality_assurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='slug',
            field=models.SlugField(default='', help_text='Slug of the lecturer', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default='', help_text='Slug of the student', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachingrecord',
            name='quality_assurance',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', help_text='Quality assurance of the course', max_length=255, null=True),
        ),
    ]
