# Generated by Django 5.1 on 2024-08-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_lecturer_slug_student_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='slug',
            field=models.SlugField(editable=False, help_text='Slug of the lecturer', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(editable=False, help_text='Slug of the student', max_length=255),
        ),
    ]
