# Generated by Django 5.1 on 2024-08-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_lecturer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='slug',
            field=models.SlugField(editable=False, help_text='Slug of the lecturer', max_length=255),
        ),
    ]
