# Generated by Django 5.1 on 2024-08-27 18:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_lecturer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 27, 19, 1, 24, 87118), help_text='Date the course is taught'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_catchup',
            field=models.BooleanField(default=False, help_text='Is this a catch-up class?'),
        ),
        migrations.AlterField(
            model_name='teachingrecord',
            name='course',
            field=models.OneToOneField(help_text='Course taught', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.course'),
        ),
        migrations.AlterField(
            model_name='teachingrecord',
            name='lecturer',
            field=models.OneToOneField(help_text='Lecturer teaching the course', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_records', to='core.lecturer'),
        ),
    ]
