# Generated by Django 5.1 on 2024-08-27 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 27, 18, 2, 53, 446212, tzinfo=datetime.timezone.utc), help_text='Date the course is taught'),
        ),
    ]
