# Generated by Django 5.1 on 2024-08-27 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 27), help_text='Date the course is taught'),
        ),
    ]
