# Generated by Django 5.1 on 2024-08-27 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_course_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingrecord',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(default='', help_text='Lecturer teaching the course', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_records', to='core.lecturer'),
            preserve_default=False,
        ),
    ]
