# Generated by Django 5.1 on 2024-08-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_teachingrecord_lecturer_course_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingrecord',
            name='course',
            field=models.OneToOneField(help_text='Course taught', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_record', to='core.course'),
        ),
    ]
