# Generated by Django 5.1 on 2024-08-28 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_teachingrecord_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 28), help_text='Date the course is taught'),
        ),
    ]
