# Generated by Django 5.1 on 2024-08-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_course_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='is_present',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.CharField(choices=[('BMS', 'BMS'), ('ICT', 'ICT')], default='ICT', help_text='Department of the lecturer: BMS or ICT', max_length=255),
        ),
        migrations.AddField(
            model_name='teachingrecord',
            name='arrival',
            field=models.TimeField(blank=True, help_text='Time of arrival of the lecturer', null=True),
        ),
        migrations.AddField(
            model_name='teachingrecord',
            name='departure',
            field=models.TimeField(blank=True, help_text='Time of departure of the lecturer', null=True),
        ),
        migrations.AddField(
            model_name='teachingrecord',
            name='is_present',
            field=models.BooleanField(default=True, help_text='Was the lecturer present?'),
        ),
        migrations.AddField(
            model_name='teachingrecord',
            name='lecture_duration',
            field=models.DurationField(blank=True, help_text='Actual duration of the course by the lecturer (Automatically calculated)', null=True),
        ),
    ]
