# Generated by Django 5.1 on 2024-08-29 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_lecturer_arrival_remove_lecturer_departure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='phone',
            field=models.CharField(blank=True, help_text="Lecturer's phone number 6xxx xxx xxx", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 29), help_text='Date the course is taught'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(editable=False, help_text='Duration of the course (Automatically calculated)'),
        ),
        migrations.AlterField(
            model_name='teachingrecord',
            name='arrival',
            field=models.TimeField(help_text='Time of arrival of the lecturer'),
        ),
        migrations.AlterField(
            model_name='teachingrecord',
            name='departure',
            field=models.TimeField(help_text='Time of departure of the lecturer'),
        ),
        migrations.AlterField(
            model_name='teachingrecord',
            name='lecture_duration',
            field=models.DurationField(editable=False, help_text='Actual duration of the course by the lecturer (Automatically calculated)'),
        ),
    ]
