# Generated by Django 5.1 on 2024-08-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_lecturer_phone_alter_course_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_present',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='phone',
            field=models.CharField(blank=True, help_text="Lecturer's phone number: 6xx xx xx xx", max_length=255, null=True),
        ),
    ]
