# Generated by Django 5.1 on 2024-08-29 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_student_is_present_alter_lecturer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the course is taught'),
        ),
    ]
