# Generated by Django 5.1 on 2024-08-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingrecord',
            name='arrival',
            field=models.TimeField(blank=True, help_text='Time of arrival of the lecturer', null=True),
        ),
        migrations.AlterField(
            model_name='teachingrecord',
            name='departure',
            field=models.TimeField(blank=True, help_text='Time of departure of the lecturer', null=True),
        ),
    ]
