# Generated by Django 5.1 on 2024-08-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_teachingrecord_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingrecord',
            name='lecture_duration',
            field=models.DurationField(blank=True, editable=False, help_text='Actual duration of the course by the lecturer (Automatically calculated)', null=True),
        ),
    ]
