# Generated by Django 5.1 on 2024-08-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_teachingrecord_lecture_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingrecord',
            old_name='arrival',
            new_name='lecturer_arrival_time',
        ),
        migrations.RenameField(
            model_name='teachingrecord',
            old_name='departure',
            new_name='lecturer_departure_time',
        ),
        migrations.RenameField(
            model_name='teachingrecord',
            old_name='lecture_duration',
            new_name='lecturer_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_catchup',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='teachingrecord',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teachingrecord',
            name='is_present',
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(help_text='Lecturer teaching the course', on_delete=django.db.models.deletion.CASCADE, related_name='course_lecturer', to='core.lecturer'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='core.student'),
        ),
        migrations.AlterField(
            model_name='studentdelegate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_delegates', to='core.course'),
        ),
        migrations.AlterField(
            model_name='studentdelegate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_delegates', to='core.student'),
        ),
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_date', models.DateField(help_text='Date the course is taught')),
                ('course_start_time', models.TimeField(help_text='Time the course started')),
                ('course_end_time', models.TimeField(help_text='Time the course ended')),
                ('course_duration', models.DurationField(blank=True, editable=False, help_text='Actual duration of the course (Automatically calculated)', null=True)),
                ('is_catchup', models.BooleanField(default=False, help_text='Is the course a catch-up course?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this course attendance was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this course attendance was last updated')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_attendance', to='core.course')),
                ('teaching_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_record_attendance', to='core.teachingrecord')),
            ],
            options={
                'verbose_name': 'Course Attendance',
                'verbose_name_plural': 'Course Attendances',
            },
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='attendance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_attendance', to='core.courseattendance'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'attendance')},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
    ]
