# Generated by Django 5.1 on 2024-08-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_arrival_teachingrecord_lecturer_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattendance',
            name='teaching_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_record_attendance', to='core.teachingrecord'),
        ),
    ]
