# Generated by Django 5.1 on 2024-08-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_student_gender_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Gender of the student: Male or Female', max_length=255),
        ),
    ]
