# Generated by Django 5.1 on 2024-09-05 14:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], help_text='Level of the class')),
                ('group', models.PositiveSmallIntegerField(help_text='Group of the class', unique=True)),
                ('semester', models.CharField(choices=[('FALL', 'FALL'), ('SPRING', 'SPRING'), ('SUMMER', 'SUMMER')], help_text='Semester of the course', max_length=255)),
                ('year', models.IntegerField(default=core.models.get_current_year, help_text="Semesters' year of the course")),
                ('department', models.CharField(choices=[('BMS', 'BMS'), ('ICT', 'ICT')], help_text='Department of the class: BMS or ICT', max_length=255)),
                ('slug', models.SlugField(editable=False, help_text='Slug of the class', max_length=255)),
                ('main_hall', models.CharField(help_text='Main hall of the class', max_length=255)),
                ('secondary_hall', models.CharField(blank=True, help_text='Secondary hall of the class', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this class level was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this class level was last updated')),
            ],
            options={
                'verbose_name': 'Class Level',
                'verbose_name_plural': 'Class Levels',
                'unique_together': {('level', 'group')},
            },
        ),
    ]
