# Generated by Django 5.1 on 2024-09-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_classlevel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdelegate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseattendance',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_level_attendance', to='core.classlevel'),
        ),
        migrations.AddConstraint(
            model_name='classlevel',
            constraint=models.UniqueConstraint(fields=('level', 'group'), name='unique_level_group'),
        ),
        migrations.AddConstraint(
            model_name='courseattendance',
            constraint=models.UniqueConstraint(fields=('course', 'teaching_record'), name='unique_course_record'),
        ),
    ]
