# Generated by Django 5.1 on 2024-09-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_studentdelegate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattendance',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_level_attendance', to='core.classlevel'),
        ),
    ]
