# Generated by Django 5.1 on 2024-09-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_courseattendance_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='group',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Group of the class', null=True, unique=True),
        ),
    ]
