# Generated by Django 5.1 on 2024-09-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_classlevel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
