# Generated by Django 5.1 on 2024-09-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_classlevel_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='about',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
